### ISSUE TITLE
View More 

### ISSUE THREAD

**Issue by Dru-Go** [anonyindian/telegraph-go#1]
View more is not appearing on my blog, Help

**Comment by celestix** [comment]
@Dru-Go please explain your issue!

**Comment by Dru-Go** [comment]
I wanted the instant view to appear on the telegram desktop apps, but now i can see that the feature is just for mobile apps

**Comment by celestix** [comment]
Yes

**Comment by ALiwoto** [comment]
> I wanted the instant view to appear on the telegram desktop apps, but now i can see that the feature is just for mobile apps

Yes! Sadly this feature is not available on Telegram Desktop yet! We sincerely apologize for this misfortune accident.
Please do open this issue on https://github.com/telegramdesktop/tdesktop, since our library can't do anything about it, thanks.
